site_name: Pierce Longamore


nav:
    - Pierce: pierce.md
    - Arrays: arrays.md
    - Queues: queues.md
    - Stack: stack.md
    - Trees: trees.md
    - Graphs: graphs.md
    - Sets: sets.md
    - Hash Tables: hash tables.md
    - Linked Lists: linked lists.md
    - Lists: lists.md

